Bugfix calling coverUrl throws error on book without cover
When calling coverUrl on a book that has no cover a error is thrown

> TypeError: Cannot read property 'substr' of undefined

This is because Archive.getBlob is called with this.cover which is
undefined.